### ISSUE TITLE
Incorrect wiki information with "Potion Effects" bonus effect

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/ArmorMechanics#12]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

As of right now, this is what the wiki states:

```
Ambient is true/false. Using true adds more particles.
HideParticles is true/false. Using true hides all particles.
```

This is incorrect:
- If Ambient is true, then particles are reduced. (False shows the regular vanilla particle amount)
- If HideParticles is false, then particles are hidden. (True shows them anyway)

### Expected Behavior

The expected behavior is for Ambient to reduce particles when true.
And HideParticles to hide particles when true instead of false.

### Steps To Reproduce

These boots currently reduce and hide particles despite the wiki saying this is not the case.

```
JumpBoots:
  Type: LEATHER_BOOTS
  Name: "&fJump Boots"
  Lore:
    - ""
    - "&7When on Feet:"
    - "&9+1 Armor"
    - "&9Jump Boost II"
  Hide_Flags: true
  Leather_Color: "#379e3e"
  Attributes:
    - GENERIC_ARMOR 1 FEET
  Bonus_Effects:
    Potion_Effects:
      - JUMP-2-true-false-false
```

### Frequency

100% of the time.

### Version and Log

This is a wiki issue, so no log is needed.
The latest version is still used.

![image](https://user-images.githubusercontent.com/29287160/213481750-3602905e-3e77-4b23-a95f-687e756057d9.png)
