### ISSUE TITLE
Could not pass event MythicDropLoadEvent to ArmorMechanics v3.0.2

### ISSUE THREAD

**Issue by Abadodod** [WeaponMechanics/ArmorMechanics#17]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Unless mythicmobs plugin is reloaded, the mobs will not drop the armormchanics armor created by the user.

### Expected Behavior

Without reloading mythicmobs, the mythicmobs plugin should be able to register armor created in armormechanics plugin in its droptable.

### Steps To Reproduce

1. Close the server (if on) and use this config in armor.yml

```
Draconic_Boots:
  Type: NETHERITE_BOOTS
  Name: "&eDraconic Boots"
  Lore:
    - "Dragon Tough Scales"
  Unbreakable: true
  Attributes:
    - GENERIC_MAX_HEALTH 10 feet
    - GENERIC_KNOCKBACK_RESISTANCE 1 feet
    - GENERIC_MOVEMENT_SPEED 0.03 feet
    - GENERIC_ARMOR 5 feet
    - GENERIC_ARMOR_TOUGHNESS 10 feet
  Enchantments:
    - PROTECTION 11
    - PROJECTILE_PROTECTION 11
    - BLAST_PROTECTION 11
    - FIRE_PROTECTION 11
    - FEATHER_FALLING 11
```

2. Add a droptable with this armor in the drops.yml in mythicmobs. And make a mob with the drop

-----------
Drops.yml
----------
```
ItemDrops:
  Drops:
  - armorMechanicsArmor{armor=Draconic_Boots} 1 1
```

----------
Mobs.yml
----------
```
Randommob:
  Drops:
  - ItemDrops
```
 
4. Start the server
5. Check console for error
6. Kill the "RandomMob" and it wont drop the armor

### Frequency

The error happens all of the time unless mythicmobs is reloaded once

### Version and Log

https://paste.gg/p/anonymous/1f28d31b9b354935bbd53132f1a082aa

### Anything else?

no
