### ISSUE TITLE
Automatic Armor Updates

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/ArmorMechanics#4]
### Description

Sometimes server admins will need to be able to change properties of armor *AFTER* it is distributed to players. ArmorMechanics needs a way to update these old pieces of armor to an exact copy of the new armor. This way, players won't gain an unfair advantage/disadvantage after balance changes. 

This should be done whenever any entity equips armor. 

Requested and paid for by "dice".

### Configuration

In config.yml
```yaml
# Settings this to true will cause ArmorMechanics to delete any armor item that
# no longer exists in config. We have this disabled by default, as this may annoy your playerbase
Delete_Old_Armor: false

# Settings this to false will give you a *MINOR* performance benefit. However,
# any armor that already exists will no longer be updated if you change it in
# config. If you don't understand those implications, leave this to be true.
#
# This option will also prevent players from effectively renaming, enchanting
# or modifying your armor, since it will be reset when they wear it.
Update_Armor: true
```
