### ISSUE TITLE
De-active Bullet_Resistance when Armor's durability is 0

### ISSUE THREAD

**Issue by O-FLOYER** [WeaponMechanics/ArmorMechanics#8]
### Description

https://cdn.discordapp.com/attachments/940673459585966121/1036291057031319602/Desktop_2022.10.30_-_21.41.59.06.mp4
In this video will show about WeaponMechanics's bug. It won't destroy any armor, but I love this bug.
1.Is there any possible to make the armor can't be destroy but we could reduce the durability from max to 0? but it can't be destroyed.
2. And my feature is when durability of armor is 0. Bullet_Resistance will not active. Is it possible?

- [Yes ] I'm willing to pay for this feature

### Configuration

Bonus_Effects:
  Bullet_Resistance:
      Base: 0.5
      Will_not_active_when_durability_is_0: true

**Comment by CJCrafter** [comment]
I'll have to figure out what causes the bug before I can make any promises

**Comment by CJCrafter** [comment]
After looking into this a bit, I think the best way to implement this feature is to implement a custom durability system, as described by #5. Basically, instead of using Minecraft's built-in durability system, I would add a number tracking each armor piece's durability. 

```yaml
Armor_A:
  Custom_Durability:
    Count_Towards_Sets_When_Broken: <true/false>  # used for disabling full set bonus effects
    Keep_Item_When_Broken: <true/false>  #  
    Broken_Item: <ItemSerializer>  # used to replace the main armor with a "broken" or "less effective" piece of armor
    Max_Durability: <Integer>
    Show_Vanilla_Durability: <true/false>
    Calculate_Unbreaking_Enchantment: <true/false>
    Lose_Durability_Mechanics: <Mechanics>

    # The next issue is repairing. For admins, I'll add `/am fix <player>` to fully repair all ArmorMechanics
    # armors in the inventory. For normal players, I'll add:
    Durability_Per_Exp: <Integer>  # like mending from vanilla
    Repair_Items:  # in anvil or repair station
      Item_0: <ItemSerializer>
        Durability_Per_Item: <Integer>
```
this is a rather complicated set of features, and it will require me to do a lot of testing to ensure there are no issues, like item duplication. For this reason, I'll give you 2 different quotes:

$65 for everything

OR

$50 for everything except the repair system 

If this is acceptable to you, here is my [paypal link](https://www.paypal.com/paypalme/cjcrafter). Make sure to send me a message afterwards.
